name: CI

on:
  push:
    paths:
      - 'design/**/*.mmd'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  build-mermaid:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate Mermaid PNGs
        run: |
          mkdir -p art/autogen
          find design -type f -name "*.mmd" | while read f; do
            out="art/autogen/$(basename "${f%.mmd}").png"
            echo "Rendering $f -> $out"
            mmdc -i "$f" -o "$out"
          done

      - name: Upload PNGs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mermaid-diagrams
          path: art/autogen/*.png
          if-no-files-found: ignore

      - name: Commit generated images back to repo
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add art/autogen/*.png || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(autogen): update Mermaid diagrams [skip ci]"
          git push
