#!/usr/bin/env bash
set -euo pipefail
DOCS_ROOT="FieldOfHorrors/docs"
INDEX_FILE="$DOCS_ROOT/README.md"

title_case() { # turn filename or dir into Title Case
  local s="$*"
  s="${s//-/ }"; s="${s//_/ }"
  awk '{
    for(i=1;i<=NF;i++){
      $i=toupper(substr($i,1,1)) tolower(substr($i,2))
    }
    print
  }' <<<"$s"
}

echo "# Field Of Horrors — Docs Index" > "$INDEX_FILE"
echo "" >> "$INDEX_FILE"
echo "_Auto-generated by tools/gen_docs_index.sh — do not edit by hand._" >> "$INDEX_FILE"
echo "" >> "$INDEX_FILE"

# Top-level sections (directories)
find "$DOCS_ROOT" -mindepth 1 -maxdepth 1 -type d | sort | while read -r dir; do
  rel="${dir#$DOCS_ROOT/}"
  [ "$rel" = ".git" ] && continue
  echo "## $(title_case "$rel")" >> "$INDEX_FILE"
  echo "" >> "$INDEX_FILE"

  # list markdown and mermaid files within each section (depth 2)
  while IFS= read -r -d '' f; do
    relf="${f#FieldOfHorrors/}"
    name="$(basename "$f")"
    # skip the index itself
    [ "$relf" = "docs/README.md" ] && continue
    # human label from filename (drop extension)
    label="${name%.*}"
    echo "- [$(title_case "$label")]($relf)" >> "$INDEX_FILE"
  done < <(find "$dir" -type f \( -name "*.md" -o -name "*.mmd" \) -print0 | sort -z)

  echo "" >> "$INDEX_FILE"
done

# Also list root-level docs (if any)
ROOT_MD=$(find "$DOCS_ROOT" -maxdepth 1 -type f \( -name "*.md" -o -name "*.mmd" \) ! -name "README.md" | sort)
if [ -n "$ROOT_MD" ]; then
  echo "## Root" >> "$INDEX_FILE"
  echo "" >> "$INDEX_FILE"
  while read -r f; do
    [ -z "$f" ] && continue
    relf="${f#FieldOfHorrors/}"
    label="$(basename "${f%.*}")"
    echo "- [$(title_case "$label")]($relf)" >> "$INDEX_FILE"
  done <<<"$ROOT_MD"
  echo "" >> "$INDEX_FILE"
fi

echo "✅ Docs index written to $INDEX_FILE"
