@startuml
skinparam dpi 180
rectangle Player {
  component Classes
  component Inventory
  component Prestige
}
rectangle Systems {
  component ScoreBoard
  component Seasons
  component Fusion
}
Player --> ScoreBoard
Prestige --> Seasons
Classes --> Fusion
@enduml
