name: Label Policy
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize, ready_for_review]
permissions:
  pull-requests: read
jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Require type:* and area:* labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 2
          labels: |
            type:design,type:feature,type:bug,type:chore,type:docs,type:test
            area:arena,area:weapons,area:telegraphs,area:ux,area:telemetry,area:narrative,area:build
