name: Link Check (Lychee)
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >
            --config .github/lychee.toml
            --verbose
            --no-progress
            --exclude-mail
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
